#!/usr/bin/env bash
# Configure server to listen on port 80

# Remoive nginx configuration to fix error
rm /etc/nginx/sites-enabled/default

# configure nginx to listen to port 80 and restart
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart

