#!/usr/bin/env bash
# Configure server to listen on port 80 of all server's active IPv4 IPs

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid

# terminates the initial nginx procedures if any
#kill "$(pgrep 'nginx' | head -1)"
