#!/usr/bin/env bash
# Configure server to listen on port 80 of all server's active IPv4 IPs

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart


# terminates the initial nginx procedures if any
kill "$(pgrep 'nginx' | head -1)"
