#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process

case "$1" in
    "start")
        ./manage_my_process start
        ;;
    "stop")
        ./manage_my_process stop
        ;;
    "restart")
        ./manage_my_process restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
