#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.  using the while loop + IFS.

while IFS=':' read -r username x userid groupid x user_info homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell."
    echo "USER ID's place is protected by the passcode $user_info, more info about the user here: $userid"
done < /etc/passwd
