#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes. Use while loop

hour=0

while [ $hour -le 12 ]
do
    minute=1
    echo "Hour: $hour"
    while [ $minute -le 59 ]
    do
	echo "$minute"
        ((minute++))
    done
    ((hour++))
done | head -n 70
